.TH UTF8TOLATIN1 1 LOCAL

.SH NAME
utf8tolatin1

.SH SYNOPSIS
.B utf8tolatin1
< infile > outfile

.SH DESCRIPTION
.I Utf8tolatin1
reads utf-8 encoded text on stdin and writes latin1 (iso8859-1) encoded
text on stdout.

.SH AUTHOR
Copyright (C) 2002 Ulric Eriksson

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston,
MA 02111-1307, USA.

