INSERT {
	GRAPH example:graphA {
		example:resource a example:A ;
			example:p 42
	}
}
DELETE {
	GRAPH example:graphA {
		example:resource example:p 42
	}
}
INSERT {
	GRAPH example:graphB {
		example:resource a example:A ;
			example:p 42
	}
}
