INSERT {
	test:1 a test:A ; test:p "bananas lemons lemons" .
	test:2 a test:A ; test:p "bananas bananas lemons" .
	test:3 a test:A ; test:o "bananas" .
	test:4 a test:A ; test:p "bananas" ; test:o "bananas lemons" .

	test:5 a test:A ; test:p "oranges!" .
	test:6 a test:A ; test:q "oranges", "oranges and oranges" .

        test:10 a test:A ; test:p "The The" .
        test:11 a test:A ; test:p "The thespian stands over the table" .
        test:12 a test:A ; test:p "Therefore, thee themed the thetical thespian therein theatricalizing thetic" .
}
