INSERT {
	test:1 a test:A ; test:p "bananas lemons lemons" .
	test:2 a test:A ; test:p "bananas bandanas lemons" .
	test:3 a test:A ; test:o "bananas" .
	test:4 a test:A ; test:p "bananas lemons" ; test:o "bananas" .

	test:5 a test:A ; test:p "oranges!" .
	test:6 a test:A ; test:q "oranges", "oranges and oranges" .
}
