.TH tracker-status-icon.cfg 5 "October 2009" GNU "Configuration Files"

.SH NAME
tracker-status-icon.cfg \- Configuration file for tracker-status-icon

.SH DESCRIPTION
This file resides in $HOME/.config/tracker/ and uses the common .ini format, i.e.

.PP
  [Group]
  # Comment
  Key=Value

.SH SECTIONS

.SS [General]
.TP
.B Visibility
The tracker-status-icon application appears in the notification area
and its visibility is decided by this config option. It can be
displayed either never, always or only when there is work being done
by a data miner. Values for this setting are: 0=Never, 1=When active,
2=Always.

.SH SEE ALSO
.BR tracker-status-icon (1),
.BR tracker-status (1),
.BR tracker-preferences (1).
