.TH tracker-stats 1 "July 2009" GNU "User Commands"

.SH NAME
tracker-stats \- Provides statistics on the data available for querying

.SH SYNOPSIS
\fBtracker-stats\fR [\fIOPTION\fR...]

.SH DESCRIPTION
.B tracker-stats
takes no arguments and returns statistics based on the ontology
classes outlined in the
.B Nepomuk
ontology specification. These classes can be used to further query
more information using
.B SparQL
with
.B tracker-sparql.

.SH OPTIONS
.TP
.B \-?, \-\-help
Show a brief help message.
.TP
.B \-V, \-\-version
Print version.

.SH SEE ALSO
.BR tracker-store (1),
.BR tracker-control (1),
.BR tracker-sparql (1),
.BR tracker-info (1).
.TP
.BR http://nepomuk.semanticdesktop.org/
.TP
.BR http://www.w3.org/TR/rdf-sparql-query/
