.TH tracker-search-tool 1 "July, 2007" GNU "User Commands"

.SH NAME
tracker-search-tool \- Gnome Tracker Search Tool

.SH SYNOPSIS
\fBtracker-search-tool\fR [\fIoptions\fR] [\fITERMS\fR]

.SH DESCRIPTION
.B tracker-search-tool
is a graphical search front end for GNOME to Tracker. It is similar to
the command line tool
.B tracker-search.
If \fITERMS\fR are provided, a search is performed using those
\fITERMS\fR initially when tracker-search-tool is started. They are
not required to start the application.

.SH OPTIONS
.TP
\fB\-V, \fB-\-version\fR
Print version.

.SH SEE ALSO
.BR tracker-search (1),
.BR tracker-sparql (1),
.BR tracker-store (1),
