.TH tracker-tag 1 "July 2009" GNU "User Commands"

.SH NAME
tracker-tag \- Add, remove and list tags.

.SH SYNOPSIS
\fBtracker-tag\fR
[\fIOPTION...\fR] FILE [\fIFILE...\fR]

.SH DESCRIPTION
.B tracker-tag
allows the caller add tags, remove tags and list tags by URN or to
list all tags and the files associated with them.

The \fIFILE\fR argument can be either a local path or a URI. It also
does not have to be an absolute path.

.SH OPTIONS
.TP
.B \-?, \-\-help
Show summary of options.
.TP
.B \-l, \-\-limit=N
Limit search to N results. The default is 512.
.TP
.B \-o, \-\-offset=N
Offset the search results by N. For example, start at item number 10
in the results. The default is 0.
.TP
.B \-r, \-\-or-operator
Use OR for search terms instead of AND (the default)
.TP
.B \-t, \-\-list
List all tags. Results include the number of files associated with
that tag and the tag's unique identifier. You can show the files
associated with each tag by using --show-files.
.TP
.B \-s, \-\-show-files
Show the files associated with each tag. This option is ONLY available
WITH the
.B --list
option.
.TP
.B \-a, \-\-add=TAG
Add a tag with the name \fITAG\fR. If no \fIFILE\fR arguments are
specified, the tag is simply created (if it didn'talready exist) and
no files are associated with it. Multiple \fIFILE\fR arguments can be
specified.
.TP
.B \-d, \-\-delete=TAG
Delete a tag with the name \fITAG\fR. If no \fIFILE\fR arguments are
specified, the tag is deleted for ALL files. If \fIFILE\fR arguments
are specified, only those files have the \fITAG\fR deleted.
.TP
.B \-e, \-\-description=STRING
This option ONLY applies when using
.B \-\-add
and provides a description to go with the tag label according to
\fISTRING\fR.
.TP
.B \-V, \-\-version
Print version.

.SH SEE ALSO
.BR tracker-store (1),
.BR tracker-sparql (1),
.BR tracker-search (1),
.BR tracker-info (1).
