.TH tracker-search 1 "July 2009" GNU "User Commands"

.SH NAME
tracker-search \- Search all content for keywords

.SH SYNOPSIS
.B tracker-search 
[OPTIONS]
.I EXPRESSION

.SH DESCRIPTION
.B tracker-search
searches all indexed content for \fIEXPRESSION\fR.
.TP
\fIEXPRESSION\fR
One or more terms to search. The default operation is a logical AND.

.SH OPTIONS
.TP
\-?, \-\-help
Give a short help message.
.TP
\-l, \-\-limit=N
Limit search to N results. The default is 512.
.TP
\-o, \-\-offset=N
Offset the search results by N. For example, start at item number 10
in the results. The default is 0.
.TP
\-d, \-\-detailed
Give more information in the search results.

.SH SEE ALSO
.BR tracker-store (1),
.BR tracker-stats (1),
.BR tracker-tag (1),
.BR tracker-info (1).
