.TH tracker-tag 1 "July 2009" GNU "User Commands"

.SH NAME
tracker-tag \- Add, remove and list tags.

.SH SYNOPSIS
.nf
\fBtracker tag\fR \fIFILE1\fR [\fIFILE2\fR ...] [\-l <limit>] [\-o <offset>] [\-r]
\fBtracker tag\fR \-t [[\fITAG1\fR] [\fITAG2\fR] ...] [\-s] [\-r]
\fBtracker tag\fR \-a <\fITAG\fR> [-e <description>] 
\fBtracker tag\fR \-d <\fITAG\fR>
.fi

.SH DESCRIPTION
List tags for local files or by the tag labels themselves if \-t is used.

It's also possible to manage tags with the \-a and and \-d options.

The \fIFILE\fR argument can be either a local path or a URI. It also
does not have to be an absolute path.

.SH OPTIONS
.TP
.B \-t, \-\-list
List all tags. Results include the number of files associated with
that tag and the tag's unique identifier. You can show the files
associated with each tag by using --show-files.

The \fITAG\fR arguments are optional. If no \fITAG\fR argument
is specified, all tags are listed. If one or more \fITAG\fRs are
given, either matching tags are listed (OR condition). For example,
this will match any tags named either \fIfoo\fR, \fIbar\fR or
\fIbaz\fR:

.nf
$ tracker-tag -t foo bar baz
.fi

.TP
.B \-s, \-\-show-files
Show the files associated with each tag. This option is ONLY available
WITH the
.B --list
option.
.TP
.B \-a, \-\-add=TAG
Add a tag with the name \fITAG\fR. If no \fIFILE\fR arguments are
specified, the tag is simply created (if it didn'talready exist) and
no files are associated with it. Multiple \fIFILE\fR arguments can be
specified.
.TP
.B \-d, \-\-delete=TAG
Delete a tag with the name \fITAG\fR. If no \fIFILE\fR arguments are
specified, the tag is deleted for ALL files. If \fIFILE\fR arguments
are specified, only those files have the \fITAG\fR deleted.
.TP
.B \-e, \-\-description=STRING
This option ONLY applies when using
.B \-\-add
and provides a description to go with the tag label according to
\fISTRING\fR.
.TP
.B \-l, \-\-limit=N
Limit search to N results. The default is 512.
.TP
.B \-o, \-\-offset=N
Offset the search results by N. For example, start at item number 10
in the results. The default is 0.
.TP
.B \-r, \-\-and-operator
Use AND operator for search terms instead of OR (the default). For
example:

.nf
$ tracker-tag -s -t sliff sloff
.fi

Should show files in the database that have both the \fIsliff\fR and
\fIsloff\fR tags.

.SH ENVIRONMENT
.TP
.B TRACKER_SPARQL_BACKEND
This option allows you to choose which backend you use for connecting
to the database. This choice can limit your functionality. There are
three settings.

With "\fBdirect\fR" the connection to the database is made directly to
the file itself on the disk, there is no intermediary daemon or
process. The "\fBdirect\fR" approach is purely \fIread-only\fR.

With "\fBbus\fR" the \fBtracker-store\fR process is used to liase with
the database queuing all requests and managing the connections via an
IPC / D-Bus. This adds a small overhead \fIBUT\fR this is the only
approach you can use if you want to \fIwrite\fR to the database.

With "\fBauto\fR" the backend is decided for you, much like it would
be if this environment variable was undefined.

.SH SEE ALSO
.BR tracker-store (1),
.BR tracker-sparql (1),
.BR tracker-search (1),
.BR tracker-info (1).
