.TH tracker-search 1 "July 2009" GNU "User Commands"

.SH NAME
tracker-search \- Search all content for keywords

.SH SYNOPSIS
\fBtracker-search\fR [\fIOPTION\fR...] \fIEXPRESSION\fR [\fIEXPRESSION\fR...]

.SH DESCRIPTION
.B tracker-search
searches all indexed content for \fIEXPRESSION\fR.
.TP
\fIEXPRESSION\fR
One or more terms to search. The default operation is a logical AND.
For logical OR operations, see -r.

The search terms can also be applied to the following options:
.B \-\-files,
.B \-\-folders,
.B \-\-music-albums,
.B \-\-music-artists,
.B \-\-music,
.B \-\-images,
.B \-\-videos
and
.B \-\-documents.

.SH OPTIONS
.TP
.B \-?, \-\-help
Give a short help message.
.TP
.B \-l, \-\-limit=N
Limit search to N results. The default is 512.
.TP
.B \-o, \-\-offset=N
Offset the search results by N. For example, start at item number 10
in the results. The default is 0.
.TP
.B \-r, \-\-or-operator
Use OR for search terms instead of AND (the default)
.TP
.B \-d, \-\-detailed
Show more detailed results (only applies to general search)
.TP
.B \-f, \-\-files
Search for files in ascending order.
.TP
.B \-e, \-\-folders
Search for folders in ascending order.
.TP
.B \-a, \-\-music-albums
Search for music albums. This also lists the song count and the sum of
the duration of all songs associated with each album.
.TP
.B \-s, \-\-music-artists
Search for music artists.
.TP
.B \-u, \-\-music
Search for music in ascending order. This returns a list of files.
.TP
.B \-l, \-\-images
Search for images in ascending order. This returns a list of files.
.TP
.B \-v, \-\-videos
Search for videos in ascending order. This returns a list of files.
.TP
.B \-u, \-\-documents
Search for documents in ascending order. This returns a list of files.
.TP
.B \-V, \-\-version
Print version.

.SH SEE ALSO
.BR tracker-store (1),
.BR tracker-stats (1),
.BR tracker-tag (1),
.BR tracker-info (1).
