.TH tracker-extract.cfg 5 "September 2009" GNU "Configuration Files"

.SH NAME
tracker-extract.cfg \- Configuration file for tracker-extract

.SH DESCRIPTION
This file resides in $HOME/.config/tracker/ and uses the common .ini format, i.e.

.PP
  [Group]
  # Comment
  Key=Value

.SH SECTIONS

.SS [General]
.TP
.B Verbosity
Log verbosity, 0=errors, 1=minimal, 2=detailed, 3=debug.
.TP
.B Max_Bytes
Maximum number of UTF-8 encoded bytes to extract [0->10485760]

.SH SEE ALSO
.BR tracker-extract (1),
.BR tracker-fts.cfg (5),
.BR tracker-miner-fs.cfg (5),
.BR tracker-store.cfg (5).