.TH tracker-store 1 "September 2009" GNU "User Commands"

.SH NAME
tracker-store \- database indexer and query daemon

.SH SYNOPSIS
\fBtracker-store\fR [\fIOPTION\fR...]

.SH DESCRIPTION
.B tracker-store
provides both a powerful database daemon which allows clients to query
or update their data using the highly descriptive
.B SPARQL
language.
.PP
.B tracker-store
does not do any file crawling or any mining of data itself, instead
other processes do that and serves as a daemon waiting for such
requests from application miners like
.B tracker-miner-fs.
.PP
For help on how to configure this daemon, see the man page for
.B tracker-store.cfg.

.SH OPTIONS
.TP
.B \-?, \-\-help
A brief help message including some examples.
.TP
.B \-V, \-\-version
Returns the version of this binary.
.TP
.B \-v, \-\-verbosity={0|1|2|3}
Sets the logging level, 0=errors, 1=minimal, 2=detailed, 3=debug.
.TP
.B \-r, \-\-force-reindex
This forces tracker-store to remove databases and to recreate fresh
databases ready for data insertion from the miners. For more
information about the miners, see
.B tracker-miner-fs.
.TP
.B \-m, \-\-low-memory
This changes the behavior of the database manager and some other
parts of
.B tracker-store
to be optimized for lower memory systems by lowering database
connection cache sizes and page sizes for example. This may slow down
indexing performance.
.TP
.B \-n, \-\-readonly-mode
This starts
.B tracker-store
in a mode which disables writing to the database. Only
.B SPARQL
read requests can be serviced if this option is used.

.SH ENVIRONMENT
.TP
.B TRACKER_DB_SQL_DIR
This is the directory which tracker uses to load the .sql files from.
These are needed on each invocation of tracker-store. If unset it will
default to the correct place. This is used mainly for testing
purposes.

.TP
.B TRACKER_DB_ONTOLOGIES_DIR
This is the directory which tracker uses to load the .ontology files
from. If unset it will default to the correct place. This is used
mainly for testing purposes.

.TP
.B TRACKER_LANGUAGE_STOP_WORDS_DIR
This is the directory which tracker uses to load the stop words
dictionaries from. If unset it will default to the correct place. This
is used mainly for testing purposes.

.TP
.B TRACKER_STORE_MAX_TASK_TIME
This is maximum time allowed for a process to finish before interruption
happens. The actual moment of interruption depends also on the frequency of
checks. The value 0 indicates no interruption.
This environment variable is used mainly for testing purposes.

.SH FILES
.I $HOME/.config/tracker/tracker-store.cfg
.I $HOME/.config/tracker/tracker-fts.cfg

.SH NOTES
.B tracker-store
is highly bound to the D-Bus freedesktop project. A D-Bus session is
needed for all Tracker processes to communicate between each other.
D-Bus is our acting IPC. See
.BR dbus-daemon(1)
for more information.

.SH SEE ALSO
.BR tracker-applet (1),
.BR tracker-search-tool (1),
.BR tracker-search (1),
.BR tracker-tag (1),
.BR tracker-stats (1),
.BR tracker-services (1),
.BR tracker-info (1),
.BR tracker-status (1).

.BR tracker-store.cfg (5),
.BR tracker-fts.cfg (5).

.BR http://www.w3.org/TR/rdf-sparql-query/

.BR dbus-daemon (1),

.BR http://www.freedesktop.org/wiki/Software/dbus
