.TH tracker-files 1 "July 2007" GNU "User Commands"

.SH NAME
tracker-files \- Return files filtered by the mime type or their category
(called ServiceType)

.SH SYNOPSIS
.B tracker-files
[-s ServiceType|-m MimeType]

.SH DESCRIPTION
.B tracker-files
returns files that match the ServiceType or the mime-type provided.

.SH OPTIONS
.TP
\-s ServiceType
Specify the kind of the files you want to find. For more information on
valid ServiceType see
.BR tracker-services (1).

.TP
\-m MimeType
Specify the mime-type of the files you want to find; see
http://www.iana.org/assignments/media-types/ for the complete list of
existing mime-type.

.SH SEE ALSO
.BR trackerd (1),
.BR tracker-services (1).
