.TH tracker-stats 1 "July 2009" GNU "User Commands"

.SH NAME
tracker-stats \- Provides statistics on the data indexed

.SH SYNOPSIS
\fBtracker-stats\fR [\fIOPTION\fR...] [[\fIEXPRESSION\fR...] [\fIEXPRESSION\fR...]]

.SH DESCRIPTION
Display statistics about RDF classes in and how many of each exist for
the data set that has been indexed.

By default, only common and useful classes are shown, e.g.
nfo:Document or nfo:Folder, for a full set of statistics, see the
.B\-\-all
option.

If one or more \fIEXPRESSION\fR is given, the statistics returned are
filtered to only include information about RDF types matching
\fIEXPRESSION\fR (case folded and matching accented variants).

The RDF classes are detailed by the
.B Nepomuk
ontology specification. These classes can be used to further query
more information using
.B SparQL
with
.B tracker-sparql.

.SH OPTIONS
.TP
.B \-h, \-\-help
Show a brief help message.
.TP
.B \-a, \-\-all
Display statistics about ALL RDF classes that exist in the database.
Without this option only the common RDF classes will be shown, for
example nfo:Document and nfo:FileDataObject.

This option is implied if search terms are provided to filter ALL
possible statistics.
.TP
.B \-V, \-\-version
Print version.

.SH SEE ALSO
.BR tracker-store (1),
.BR tracker-control (1),
.BR tracker-sparql (1),
.BR tracker-info (1).
.TP
.BR http://nepomuk.semanticdesktop.org/
.TP
.BR http://www.w3.org/TR/rdf-sparql-query/
