.TH tracker-needle 1 "December, 2010" GNU "User Commands"

.SH NAME
tracker-needle \- GNOME user interface similar to tracker-search

.SH SYNOPSIS
.B tracker-needle

.SH DESCRIPTION
.B tracker-needle
is a graphical front end for Tracker which has similar features to
.BR tracker-search (1).

.SH SEE ALSO
.BR tracker-search (1),
.BR tracker-sparql (1),
.BR tracker-store (1),

.BR http://live.gnome.org/Tracker/SupportedFormats
