.TH tracker-import 1 "July 2009" GNU "User Commands"

.SH NAME
tracker-import \- Imports Turtle file data into the database

.SH SYNOPSIS
\fBtracker-import\fR 
\fIFILE\fR

.SH DESCRIPTION
.B tracker-import
allows data to be imported to the database by providing files with
Turtle content.

Multiple \fIFILE\fR arguments can be provided to import data from
multiple files.

The \fIFILE\fR argument can be either a local path or a URI. It also
does not have to be an absolute path.

.SH OPTIONS
.TP
.B \-?, \-\-help
Show summary of options.
.TP
.B \-V, \-\-version
Print version.

.SH SEE ALSO
.BR tracker-store (1),
.BR tracker-sparql (1),
.BR tracker-info (1).
.TP
.BR Turtle.
