.TH tracker-stats 1 "July 2007" GNU "User Commands"

.SH NAME
tracker-stats\- command line tool that provides statistics on files
indexed by
.B trackerd 

.SH SYNOPSIS
.B tracker-stats [OPTIONS] 

.SH DESCRIPTION
.B tracker-stats
returns statistics on files indexed by tracker indexing daemon, ordered
by service type.

.SH OPTIONS
.TP
\-?, --help
Show a brief help message.

.SH "SEE ALSO"
.BR trackerd (1),
.BR tracker-status (1),
.BR tracker-services (7).
