.TH tracker-control 1 "September 2009" GNU "User Commands"

.SH NAME
tracker-control \- Manage Tracker processes and data

.SH SYNOPSIS
\fBtracker-control\fR [\fIOPTION\fR...]

.SH DESCRIPTION
.B tracker-control
lists all tracker related processes when no
\fIOPTION\fRs are specified.

To see the status of the miners and the store, use 
.B tracker-status.
You can pause or resume miners and also see which ones
are running and which ones are installed.

.SH OPTIONS
.TP
.B \-?, \-\-help
Show summary of options.
.TP
.B \-V, \-\-version
Returns the version of this binary.
.TP
.B \-k, \-\-kill=[all|store|miners]
This uses SIGKILL to stop all Tracker processes found matching the
parameter, if no extra parameter is passed,
.B all
will be assumed. This is not advised unless you are having problems
stopping Tracker in the first place. This
.B GUARANTEES
death.
.TP
.B \-t, \-\-terminate=[all|store|miners]
This uses SIGTERM to stop all Tracker processes found matching the
parameter, if no extra parameter is passed,
.B all
will be assumed. This is recommended over \-\-kill because it gives
the processes time to shutdown cleanly.
.TP
.B \-r, \-\-hard-reset
This kills all processes in the same way that
.B \-\-kill
does but it also removes all databases. Restarting
.B tracker-store
re-creates the databases.
.TP
.B \-e, \-\-soft-reset
A soft reset works exactly the same way that
.B \-\-hard-reset
does, with the exception that the backup and journal are not removed.
These are restored when
.B tracker-store
is restarted.
.TP
.B \-c, \-\-remove-config
This removes all config files in $HOME/.config/tracker. All files
listed are files which were found and successfully removed.
Restarting the respective processes re-creates the default
configuration files.
.TP
.B \-s, \-\-start
Starts all miners. This indirectly starts tracker-store too because it
is needed for miners to operate properly.
.TP
.B \-m, \-\-reindex-mime-type=MIME
Re-index files which match the \fIMIME\fR type supplied. This is
usually used when installing new extractors which support \fIMIME\fR
types previously unsupported. This forces Tracker to re-index those
files. You can use 
.B \-\-reindex-mime-type
more than once per \fIMIME\fR type.
.TP
.B \-f, \-\-index-file=FILE
(Re)index a file matching the \fIFILE\fR type supplied.

.SH SEE ALSO
.BR tracker-status (1),
.BR tracker-store (1).
