.TH tracker-control 1 "September 2009" GNU "User Commands"

.SH NAME
tracker-control \- Manage Tracker processes and data

.SH SYNOPSIS
\fBtracker-control\fR [\fIOPTION\fR...]

.SH DESCRIPTION
.B tracker-control
manages and checks status of all Tracker processes and data.

Controls Tracker both at process level, and at entity level (store, miners).

To start or stop miners, you can use
.B \-\-start.
The store is started automatically by the D-Bus calls from the miners.

It also allows checking the status of the Tracker store and all data miners.
For
.B tracker-store
, the status is always
.B Idle
unless it is restoring a backup and/or replaying a journal (regardless of
load from applications or miners). For a list of common statuses, see
.B \-\-list\-common\-statuses.

The miners can be paused or resumed using this command and you can
also list miners running and available.

.SH COMMON OPTIONS
.TP
.B \-?, \-\-help
Show summary of options by group.
.TP
.B \-?, \-\-help-all
Show all groups and options.
.TP
.B \-V, \-\-version
Returns the version of this program.

.SH GENERAL OPTIONS
.TP
.B \-p, \-\-list\-processes
This lists all Tracker processes in the system.
.TP
.B \-k, \-\-kill=[all|store|miners]
This uses SIGKILL to stop all Tracker processes found matching the
parameter, if no extra parameter is passed,
.B all
will be assumed. This is not advised unless you are having problems
stopping Tracker in the first place. This
.B GUARANTEES
death.
.TP
.B \-t, \-\-terminate=[all|store|miners]
This uses SIGTERM to stop all Tracker processes found matching the
parameter, if no extra parameter is passed,
.B all
will be assumed. This is recommended over \-\-kill because it gives
the processes time to shutdown cleanly.
.TP
.B \-r, \-\-hard-reset
This kills all processes in the same way that
.B \-\-kill
does but it also removes all databases. Restarting
.B tracker-store
re-creates the databases.
.TP
.B \-e, \-\-soft-reset
A soft reset works exactly the same way that
.B \-\-hard-reset
does, with the exception that the backup and journal are not removed.
These are restored when
.B tracker-store
is restarted.
.TP
.B \-c, \-\-remove-config
This removes all config files in $HOME/.config/tracker. All files
listed are files which were found and successfully removed.
Restarting the respective processes re-creates the default
configuration files.
.TP
.B \-s, \-\-start
Starts all miners. This indirectly starts tracker-store too because it
is needed for miners to operate properly.
.TP
.B \-b, \-\-backup=PATH
Begins backing up the Tracker databases to the
.B PATH
given.
.TP
.B \-o, \-\-restore=PATH
Begins restoring a previous backup (see
.B \-\-backup
) to the Tracker databases. The
.B PATH
points to the location of the backup.

.SH STATUS OPTIONS
.TP
.B \-S, \-\-status
Show the current status of all Tracker entities (store and all available
miners).
.TP
.B \-F, \-\-follow
Follow status changes as they happen. This requires Ctrl+C to stop and
return to the command line. Each new status is put on a new line.
.TP
.B \-C, \-\-list-common-statuses
This will list statuses most commonly produced by miners and the
store. These statuses are not translated when sent over D-Bus and
should be translated by each application. These are not considered
static and are subject to change at any point.

Additionally, these statuses are not the only ones which may be
reported by a miner. There may be other states pertaining to the
specific roles of the miner in question.

.SH MINER OPTIONS
.TP
.B \-m, \-\-reindex-mime-type=MIME
Re-index files which match the \fIMIME\fR type supplied. This is
usually used when installing new extractors which support \fIMIME\fR
types previously unsupported. This forces Tracker to re-index those
files. You can use
.B \-\-reindex-mime-type
more than once per \fIMIME\fR type.
.TP
.B \-f, \-\-index-file=FILE
(Re)index a file matching the \fIFILE\fR type supplied.
.TP
.B \-l, \-\-list-miners-running
This will list all miners which have responded to a D-Bus call.
Sometimes it is helpfult to use this command with
.B \-\-list-miners-available.
.TP
.B \-a, \-\-list-miners-available
This will list all miners which are available even if they are not
running at the moment.
.TP
.B \-i, \-\-pause-details
For listing all miners which are paused and the reasons for being
paused, you can use this. It will also display the application that
requested the pause too.
.TP
.B \-\-miner=MINER
This argument is used with
.B \-\-pause
or
.B \-\-resume
to say which miner you want to pause or resume. You can use the full
D-Bus name, e.g.
.B org.freedesktop.Tracker1.Miner.Files
OR you can use the suffix, e.g.
.B Files
.TP
.B \-\-pause=REASON
The REASON here is useful to know WHY the miner should be paused. A
miner can be paused many times by multiple applications. Only when all
pauses have been resumed will it continue. If successful, a cookie
will be given to uniquely identify the request. This cookie is used to
resume the pause at a later stage.
.TP
.B \-\-resume=COOKIE
The COOKIE is given by a successful
.B \-\-pause
command. It is a number which identifies each pause request. When all
pauses have been resumed, the miner will resume working.

.SH SEE ALSO
.BR tracker-store (1).
