.TH tracker-fts.cfg 5 "September 2009" GNU "Configuration Files"

.SH NAME
tracker-fts.cfg \- Configuration file for tracker-fts.so SQLite module

.SH DESCRIPTION
This file resides in $HOME/.config/tracker/ and uses the common .ini format, i.e.

.PP
  [Group]
  # Comment
  Key=Value

.SH SECTIONS

.SS [Indexing]
.TP
.B MinWordLength=3
Set the minimum length of words to index (0->30).

.TP
.B MaxWordLength=30
Set the maximum length of words to index (0->200).

.TP
.B EnableStemmer=false
Set to true if stemming should be applied to each word. Stemming is the process
for reducing inflected and derived words to their stem, base or root form.

.TP
.B EnableUnaccent=true
Set to true if combining diacritical marks should be removed from each word.

.TP
.B IgnoreNumbers=true
Set to true if words starting with numbers should be ignored.

.TP
.B IgnoreStopWords=true
Set to true if stop words should be ignored.

.TP
.B MaxWordsToIndex=10000
Maximum unique words to index from a file's content.

.SH SEE ALSO
.BR tracker-extract.cfg (5),
.BR tracker-miner-fs.cfg (5),
.BR tracker-store.cfg (5).