.TH tracker-extract 1 "July 2007" GNU "User Commands"

.SH NAME
tracker-extract \- Extract metadata from a file.

.SH SYNOPSYS
\fBtracker-extract\fR [\fIOPTION\fR...] \fIFILE\fR...

.SH DESCRIPTION
.B tracker-extract
reads the file and mimetype provided in stdin and extract the metadata from this
file; then it displays the metadata on the standard output.

.B NOTE:
If a \fIFILE\fR is not provided then
.B tracker-extract
will run for 30 seconds waiting for DBus calls before quitting.

.SH OPTIONS
.TP
.B \-?, \-\-help
Show summary of options.
.TP
.B \-v, \-\-verbosity=N
Set verbosity to N. This overrides the config value.
Values include 0=errors, 1=minimal, 2=detailed and 3=debug.
.TP
.B \-f, \-\-file=FILE
The \fIFILE\fR to extract metadata from. The \fIFILE\fR argument can
be either a local path or a URI. It also does not have to be an absolute path.
.TP
.B \-m, \-\-mime=MIME
The \fIMIME\fR type to use for the file. If one is not provided, it
will be guessed automatically.
.TP
.B \-d, \-\-disable-shutdown
Disable shutting down after 30 seconds of inactivity.
.TP
.B \-i, \-\-force-internal-extractors
Use this option to force internal extractors over 3rd parties like
libstreamanalyzer.
.TP
.B \-m, \-\-force-module=MODULE
Force a particular module to be used. This is here as a convenience
for developers wanting to test their \fIMODULE\fR file. Only the
\fIMODULE\fR name has to be specified, not the full path. Typically, a
\fIMODULE\fR is installed to /usr/lib/tracker-0.7/extract-modules/.
This option can be used with or without the .so part of the name too,
for example, you can use
.B --force-module=foo

Modules are shared objects which are dynamically loaded at run time. These files
must have the .so suffix to be loaded and must contain the correct
symbols to be authenticated by
.B tracker-extract.
For more information see the libtracker-extract reference documentation.
.TP
.B \-V, \-\-version
Show binary version.

.SH EXAMPLES
.TP
Using command line to extract metadata from a file:

.BR 
$ tracker-extract -v 3 -f /path/to/some/file.mp3

.TP
Using a specific module to extract metadata from a file:

.BR 
$ tracker-extract -v 3 -f /path/to/some/file.mp3 -m mymodule

.SH ENVIRONMENT
.TP
.B TRACKER_EXTRACTORS_DIR
This is the directory which tracker uses to load the shared libraries
from (used for extracting metadata for specific file types). These are
needed on each invocation of tracker-store. If unset it will default
to the correct place. This is used mainly for testing purposes.

.SH SEE ALSO
.BR tracker-store (1),
.BR tracker-sparql (1),
.BR tracker-stats (1),
.BR tracker-info (1).
.TP
.BR /usr/lib/tracker-0.10/extract-modules/
