.TH tracker-tag 1 "July 2007" GNU "User Commands"

.SH NAME
tracker-tag \- Tool to get/set and search for tags and keywords

.SH SYNOPSIS
\fBtracker-tag\fR [\fIOPTIONS\fR] \fIFILE\fR...

.SH DESCRIPTION
.B tracker-tag
allows you to change and search for tags associated with a file.

.SH OPTIONS
.TP
.B \-?, \-\-help
Show summary of options.
.TP
.B \-a, \-\-add=TAG
Add specified tag to a file.
.TP
.B \-r, \-\-remove=TAG
Remove specified tag from a file.
.TP
.B \-R, \-\-remove-all
Remove all tags associated with a file.
.TP
.B \-l, \-\-list
List all tags associated with a file.
.br
If no file name is given, all known tags and their count is listed.
.TP
.B \-s, \-\-search=TAG
Search for files matching the given tag.

.SH SEE ALSO
.BR tracker-store (1),
.BR tracker-stats (1),
.BR tracker-info (1).
