.TH tracker-search-bar 1 "September 2009" GNU "User Commands"

.SH NAME
tracker-search-bar \- Search applet for the GNOME panel

.SH SYNOPSIS
.B tracker-search-bar

.SH DESCRIPTION
.B tracker-search-bar
is a graphical front end applet for the GNOME panel which allows basic
searching of common categories using Full Text Searching (FTS). This
means, that searching for \fIcar\fR will find files like
\fIcarlos.png\fR, \fIcar-tax.pdf\fR, etc.

.B tracker-search-bar
currently extends to images, videos, music, folders and documents. The
applet is meant to quickly be able to access the top hits associated
with your search terms from the desktop at any time.

.SH SEE ALSO
.BR tracker-search-tool (1),
.BR tracker-status-icon (1).
