.TH tracker-status-icon 1 "September 2009" GNU "User Commands"

.SH NAME
tracker-status-icon \- Miner status and control notification area icon

.SH SYNOPSIS
.B tracker-status-icon

.SH DESCRIPTION
.B tracker-status-icon
is a
.BR tracker-store (1)
notification area icon meant to provide a fast way to check the
status of Tracker's data miner and to be able to control those miners
with simple commands like pause and resume.

When clicking on the icon, a list of data miners is presented. In this
list there is an image to the left which indicates the paused or
non-paused state. There is also a progress bar which indicates how far
through the work load the data miner is.

Each miner can be paused/resumed by clicking on it in the menu.

From the context menu,
.B tracker-status-icon
allows the user to configure the preferences of
.B tracker-miner-fs
using the
.B tracker-preferences
application.

.SH OPTIONS
.TP
.B \-?, \-\-help
Show summary of options.
.TP
.B \-V, \-\-version
Print version.

.SH FILES
.I $HOME/.config/tracker/tracker-status-icon.cfg

.SH SEE ALSO
.BR tracker-status-icon.cfg (5),
.BR tracker-search-tool (1),
.BR tracker-preferences (1),
.BR tracker-store (1).
