.TH tracker-unique 1 "Oct 2008" GNU "User Commands"

.SH NAME
tracker-unique \- command line tool to ask for unique values of a
property in tracker.

.SH SYNOPSIS
\fBtracker-unique\fR 
[OPTIONS]
-p \fIRDFFILE\fR \fIFIELD\fR [FIELD...]

.SH DESCRIPTION
.B tracker-unique
gets all the unique values of \fIFIELD\fR
after running the RDF query in \fIRDFFILE\fR. 

.PP
More than one field can be used, and then it will return the 
unique values of the combination.

.SH OPTIONS
.TP
.B \-?, \-\-help
Show summary of options.
.TP
.B \-p, \-\-path=RDFFILE
A file containing a RDF query. (See
documentation for description of the format).
.TP
.B FIELD
A valid property in tracker. For more information on tracker
properties, see
.BR tracker-services (1)
.TP
.B \-s, \-\-service=SERVICE
Limit the query to the specified service type. For more information on
tracker services, see 
.BR tracker-services (1)
.TP
.B \-c, \-\-count=FIELD
Count different values of \fIFIELD\fR in the result of the query.
.TP
.B \-u, \-\-sum=FIELD
Add all values of \fIFIELD\fR in the result of the query.
.TP
.B \-o, \-\-desc
Sort to descending order


.SH SEE ALSO
.BR trackerd (1),
.BR tracker-services (1).

.SH AUTHOR
tracker-unique was written by Mikael Ottela <mikael.ottela@ixonos.com>.
