.TH tracker-preferences 1 "September 2009" GNU "User Commands"

.SH NAME
tracker-preferences \- Preferences editor for tracker-miner-fs

.SH SYNOPSIS
.B tracker-preferences

.SH DESCRIPTION
.B tracker-preferences
is a graphical configuration front end for the
.BR tracker-miner-fs (1)
which crawls and mines data from the filesystem to be stored in the
Tracker databases.

.SH SEE ALSO
.BR tracker-search-tool (1),
.BR tracker-store (1).
