.TH tracker-store.cfg 5 "September 2009" GNU "Configuration Files"

.SH NAME
tracker-store.cfg \- Configuration file for tracker-store

.SH DESCRIPTION
This file resides in $HOME/.config/tracker/ and uses the common .ini format, i.e.

.PP
  [Group]
  # Comment
  Key=Value

.SH SECTIONS

.SS [General]
.TP
.B Verbosity
Log verbosity, 0=errors, 1=minimal, 2=detailed, 3=debug.

.TP
.B LowMemoryMode=false
Minimizes memory use at the expense of indexing speed.

.SH SEE ALSO
.BR tracker-store (1),
.BR tracker-extract.cfg (5),
.BR tracker-fts.cfg (5),
.BR tracker-miner-fs.cfg (5).
