INSERT DATA {
  example:a  a example:A ;
             example:stringMultivalued 'foo' ;
             example:stringMultivalued 'bar' ;
             example:stringMultivalued 'baz' .
  example:b  a example:A ;
             example:stringMultivalued 'baa' .
}

# Expected to fail because DELETE DATA does not allow unbound variables
DELETE DATA {
  example:a  example:stringMultivalued ?foo .
}
