INSERT {
  example:a a example:A ;
            example:string 'foo' .
  example:b a example:A ;
            example:string 'bar' .
};

DELETE {
  example:b example:string ?s
}
INSERT {
  example:b example:string 'baz'
}
USING NAMED nrl:DefaultGraph
WHERE {
  GRAPH ?g {
    example:b example:string ?s
  }
}
