.TH tracker-status 1 "July 2007" GNU "User Commands"

.SH NAME
tracker-status\- command line tool that reports the trackerd status

.SH SYNOPSIS
.B tracker-status

.SH DESCRIPTION
.B tracker-status
Prints trackerd's status. Which can be one of the following:
.PP
Initializing, Watching, Indexing, Pending, Optimizing, Idle, Shutdown.

.SH SEE ALSO
.BR trackerd (1),
.BR tracker-stats (1)
