#!/bin/sh

convert -size 320x240   pattern:bricks       avi_src_1.png
convert -size 320x240   pattern:checkerboard avi_src_2.png
convert -size 320x240   pattern:circles      avi_src_3.png
convert -size 320x240   pattern:crosshatch   avi_src_4.png
convert -size 320x240   pattern:fishscales   avi_src_5.png

gst-launch multifilesrc location="avi_src_%01d.png" index=1 caps="image/png,framerate=\(fraction\)1/3" ! pngdec ! taginject tags="title=title,artist=artist,copyright=copyright,comment=comments,license=license,location=location,genre=genre" ! ffmpegcolorspace ! xvidenc ! avimux ! filesink location="basic_tags_1.avi"
