patterns:
  require:
    - regex: '^[^:]+: +[^ ]'
      message: "Commit message subject must have a prefix. E.g. 'tests: '"
  deny:
    - regex: '^$CI_MERGE_REQUEST_PROJECT_URL/(-/)?merge_requests/$CI_MERGE_REQUEST_IID$'
      message: "Commit message must not contain a link to its own merge request"
    - regex: '^[^:]+: [a-z]'
      message: "Commit message subject should be properly Capitalized. E.g.  'cli: Fix help subcommand'"
      where: subject
    - regex: '^\S*\.[ch]:'
      message: Commit message subject prefix should not include .c, .h, etc.
      where: subject
