#!/bin/sh

# Basic properties

#size
convert -size 320x240   pattern:checkerboard header_size_1.jpg
convert -size 640x480   pattern:checkerboard header_size_2.jpg
convert -size 1280x1024 pattern:checkerboard header_size_3.jpg
convert -size 1600x1400 pattern:checkerboard header_size_4.jpg
convert -size 11x2483   pattern:checkerboard header_size_5.jpg

#EXIF
convert -size 320x240   pattern:checkerboard exif_size_1.jpg
exiftool -exif:ImageWidth=640 -exif:ImageHeight=480 exif_size_1.jpg

#orientation
convert -size 320x240   pattern:checkerboard exif_orientation_1.jpg
exiftool -exif:Orientation=1 -n exif_orientation_1.jpg

convert -size 320x240   pattern:checkerboard exif_orientation_2.jpg
exiftool -exif:Orientation=2 -n exif_orientation_2.jpg

convert -size 320x240   pattern:checkerboard exif_orientation_3.jpg
exiftool -exif:Orientation=3 -n exif_orientation_3.jpg

convert -size 320x240   pattern:checkerboard exif_orientation_4.jpg
exiftool -exif:Orientation=4 -n exif_orientation_4.jpg

convert -size 320x240   pattern:checkerboard exif_orientation_5.jpg
exiftool -exif:Orientation=5 -n exif_orientation_5.jpg

convert -size 320x240   pattern:checkerboard exif_orientation_6.jpg
exiftool -exif:Orientation=6 -n exif_orientation_6.jpg

convert -size 320x240   pattern:checkerboard exif_orientation_7.jpg
exiftool -exif:Orientation=7 -n exif_orientation_7.jpg

convert -size 320x240   pattern:checkerboard exif_orientation_8.jpg
exiftool -exif:Orientation=8 -n exif_orientation_8.jpg

#datetime
convert -size 320x240   pattern:checkerboard exif_datetime_1.jpg
exiftool -exif:ModifyDate=2190:12:23 exif_datetime_1.jpg

convert -size 320x240   pattern:checkerboard exif_datetime_2.jpg
exiftool -exif:DateTimeOriginal=1930:12:23 exif_datetime_2.jpg
#image name
convert -size 320x240   pattern:checkerboard exif_name_1.jpg
exiftool -exif:DocumentName="Test name" exif_name_1.jpg

#artist
convert -size 320x240   pattern:checkerboard exif_artist_1.jpg
exiftool -exif:Artist="Artist name" exif_artist_1.jpg

#comment
convert -size 320x240   pattern:checkerboard exif_comment_1.jpg
exiftool -exif:UserComment="I am commenting" exif_comment_1.jpg

#description
convert -size 320x240   pattern:checkerboard exif_description_1.jpg
exiftool -exif:ImageDescription="I am describing" exif_description_1.jpg

#software
convert -size 320x240   pattern:checkerboard exif_software_1.jpg
exiftool -exif:Software="Softa" exif_software_1.jpg

#fnumber
convert -size 320x240   pattern:checkerboard exif_fnumber_1.jpg
exiftool -exif:FNumber=2.3 exif_fnumber_1.jpg

#flash
convert -size 320x240   pattern:checkerboard exif_flash_1.jpg
exiftool -exif:Flash=0x0 -n exif_flash_1.jpg

convert -size 320x240   pattern:checkerboard exif_flash_2.jpg
exiftool -exif:Flash=0x1 -n exif_flash_2.jpg

convert -size 320x240   pattern:checkerboard exif_flash_3.jpg
exiftool -exif:Flash=0x5 -n exif_flash_3.jpg

convert -size 320x240   pattern:checkerboard exif_flash_4.jpg
exiftool -exif:Flash=0x7 -n exif_flash_4.jpg

convert -size 320x240   pattern:checkerboard exif_flash_5.jpg
exiftool -exif:Flash=0x8 -n exif_flash_5.jpg

convert -size 320x240   pattern:checkerboard exif_flash_6.jpg
exiftool -exif:Flash=0x9 -n exif_flash_6.jpg

convert -size 320x240   pattern:checkerboard exif_flash_7.jpg
exiftool -exif:Flash=0xd -n exif_flash_7.jpg

convert -size 320x240   pattern:checkerboard exif_flash_8.jpg
exiftool -exif:Flash=0xf -n exif_flash_8.jpg

convert -size 320x240   pattern:checkerboard exif_flash_9.jpg
exiftool -exif:Flash=0x10 -n exif_flash_9.jpg

convert -size 320x240   pattern:checkerboard exif_flash_10.jpg
exiftool -exif:Flash=0x14 -n exif_flash_10.jpg

convert -size 320x240   pattern:checkerboard exif_flash_11.jpg
exiftool -exif:Flash=0x18 -n exif_flash_11.jpg

convert -size 320x240   pattern:checkerboard exif_flash_12.jpg
exiftool -exif:Flash=0x19 -n exif_flash_12.jpg

convert -size 320x240   pattern:checkerboard exif_flash_13.jpg
exiftool -exif:Flash=0x1d -n exif_flash_13.jpg

convert -size 320x240   pattern:checkerboard exif_flash_14.jpg
exiftool -exif:Flash=0x1f -n exif_flash_14.jpg

convert -size 320x240   pattern:checkerboard exif_flash_15.jpg
exiftool -exif:Flash=0x20 -n exif_flash_15.jpg

convert -size 320x240   pattern:checkerboard exif_flash_16.jpg
exiftool -exif:Flash=0x30 -n exif_flash_16.jpg

convert -size 320x240   pattern:checkerboard exif_flash_17.jpg
exiftool -exif:Flash=0x41 -n exif_flash_17.jpg

convert -size 320x240   pattern:checkerboard exif_flash_18.jpg
exiftool -exif:Flash=0x45 -n exif_flash_18.jpg

convert -size 320x240   pattern:checkerboard exif_flash_19.jpg
exiftool -exif:Flash=0x47 -n exif_flash_19.jpg

convert -size 320x240   pattern:checkerboard exif_flash_20.jpg
exiftool -exif:Flash=0x49 -n exif_flash_20.jpg

convert -size 320x240   pattern:checkerboard exif_flash_21.jpg
exiftool -exif:Flash=0x4d -n exif_flash_21.jpg

convert -size 320x240   pattern:checkerboard exif_flash_22.jpg
exiftool -exif:Flash=0x4f -n exif_flash_22.jpg

convert -size 320x240   pattern:checkerboard exif_flash_23.jpg
exiftool -exif:Flash=0x50 -n exif_flash_23.jpg

convert -size 320x240   pattern:checkerboard exif_flash_24.jpg
exiftool -exif:Flash=0x58 -n exif_flash_24.jpg

convert -size 320x240   pattern:checkerboard exif_flash_25.jpg
exiftool -exif:Flash=0x59 -n exif_flash_25.jpg

convert -size 320x240   pattern:checkerboard exif_flash_26.jpg
exiftool -exif:Flash=0x5d -n exif_flash_26.jpg

convert -size 320x240   pattern:checkerboard exif_flash_27.jpg
exiftool -exif:Flash=0x5f -n exif_flash_27.jpg

#focal lenght
convert -size 320x240   pattern:checkerboard exif_focal_1.jpg
exiftool -exif:FocalLength=5.3 exif_focal_1.jpg

#iso
convert -size 320x240   pattern:checkerboard exif_iso_1.jpg
exiftool -exif:ISO=5 exif_iso_1.jpg

#white balance
convert -size 320x240   pattern:checkerboard exif_white_1.jpg
exiftool -exif:WhiteBalance=0 -n exif_white_1.jpg

#metering mode
convert -size 320x240   pattern:checkerboard exif_metering_1.jpg
exiftool -exif:MeteringMode=5 -n exif_metering_1.jpg

#	{ EXIF_TAG_MAKE, "Image:CameraMake", NULL },
#	{ EXIF_TAG_MODEL, "Image:CameraModel", NULL },
#	{ EXIF_TAG_ORIENTATION, "Image:Orientation", NULL },
#	{ EXIF_TAG_EXPOSURE_PROGRAM, "Image:ExposureProgram", NULL },
#	{ EXIF_TAG_EXPOSURE_TIME, "Image:ExposureTime", fix_exposure_time },
#	{ EXIF_TAG_COPYRIGHT, "File:Copyright", NULL },


