#!/bin/sh

# Basic properties

#size
convert -size 320x240   pattern:checkerboard basic_size_1.tif
convert -size 640x480   pattern:checkerboard basic_size_2.tif
convert -size 1280x1024 pattern:checkerboard basic_size_3.tif
convert -size 1600x1400 pattern:checkerboard basic_size_4.tif
convert -size 11x2483   pattern:checkerboard basic_size_5.tif

#EXIF
#convert -size 320x240   pattern:checkerboard exif_size_1.tif
#exiftool -exif:ImageWidth=640 -exif:ImageHeight=480 exif_size_1.tif

#orientation
convert -size 320x240   pattern:checkerboard exif_orientation_1.tif
exiftool -exif:Orientation=1 -n exif_orientation_1.tif

convert -size 320x240   pattern:checkerboard exif_orientation_2.tif
exiftool -exif:Orientation=2 -n exif_orientation_2.tif

convert -size 320x240   pattern:checkerboard exif_orientation_3.tif
exiftool -exif:Orientation=3 -n exif_orientation_3.tif

convert -size 320x240   pattern:checkerboard exif_orientation_4.tif
exiftool -exif:Orientation=4 -n exif_orientation_4.tif

convert -size 320x240   pattern:checkerboard exif_orientation_5.tif
exiftool -exif:Orientation=5 -n exif_orientation_5.tif

convert -size 320x240   pattern:checkerboard exif_orientation_6.tif
exiftool -exif:Orientation=6 -n exif_orientation_6.tif

convert -size 320x240   pattern:checkerboard exif_orientation_7.tif
exiftool -exif:Orientation=7 -n exif_orientation_7.tif

convert -size 320x240   pattern:checkerboard exif_orientation_8.tif
exiftool -exif:Orientation=8 -n exif_orientation_8.tif
