#!/bin/sh

# Basic properties

#size
convert -size 320x240   pattern:checkerboard basic_size_1.png
convert -size 640x480   pattern:checkerboard basic_size_2.png
convert -size 1280x1024 pattern:checkerboard basic_size_3.png
convert -size 1600x1400 pattern:checkerboard basic_size_4.png
convert -size 11x2483   pattern:checkerboard basic_size_5.png

#orientation
convert -size 320x240   pattern:checkerboard xmp_exif_orientation_1.png
exiftool -xmp:Orientation=1 -n xmp_exif_orientation_1.png

convert -size 320x240   pattern:checkerboard xmp_exif_orientation_2.png
exiftool -xmp:Orientation=2 -n xmp_exif_orientation_2.png

convert -size 320x240   pattern:checkerboard xmp_exif_orientation_3.png
exiftool -xmp:Orientation=3 -n xmp_exif_orientation_3.png

convert -size 320x240   pattern:checkerboard xmp_exif_orientation_4.png
exiftool -xmp:Orientation=4 -n xmp_exif_orientation_4.png

convert -size 320x240   pattern:checkerboard xmp_exif_orientation_5.png
exiftool -xmp:Orientation=5 -n xmp_exif_orientation_5.png

convert -size 320x240   pattern:checkerboard xmp_exif_orientation_6.png
exiftool -xmp:Orientation=6 -n xmp_exif_orientation_6.png

convert -size 320x240   pattern:checkerboard xmp_exif_orientation_7.png
exiftool -xmp:Orientation=7 -n xmp_exif_orientation_7.png

convert -size 320x240   pattern:checkerboard xmp_exif_orientation_8.png
exiftool -xmp:Orientation=8 -n xmp_exif_orientation_8.png
