[General]
Description=Files
Enabled=true

[Monitors]
Directories=
RecurseDirectories=

[Ignored]
Directories=po;CVS;.svn;.git
Files=*~*;*.o;*.la;*.lo;*.loT;*.in;*.csproj;*.m4;*.rej;*.gmo;*.orig;*.pc;*.omf;*.aux;*.tmp;*.po;*.vmdk;*.vm*;*.nvram;*.part;autom4te;conftest;confstat;Makefile;SCCS;litmain.sh;libtool;config.status;confdefs.h;

[Index]
Service=
MimeTypes=
Files=

[Specific]
# Options specific to this module
