INSERT {
  ([ a example:A ; example:label "elem1" ]
   [ a example:A ; example:label "elem2" ]
   [ a example:A ; example:label "elem3" ]
   [ a example:A ; example:label "elem4" ] ) a example:A ; example:label 'root' .
}