SELECT ?s fn:year-from-dateTime (?v) fn:month-from-dateTime (?v) fn:day-from-dateTime (?v) fn:hours-from-dateTime (?v) fn:minutes-from-dateTime (?v) fn:seconds-from-dateTime (?v)
WHERE {
	?s a example:A ;
	   example:p ?v
}
ORDER BY ASC(?s)
