PREFIX ex: <http://example/>
PREFIX ns: <http://www.w3.org/2005/xpath-functions#>

SELECT fn:string-join((?s,?t,?u),"|")
{ OPTIONAL { ?_x ex:s ?s . }
  OPTIONAL { ?_x ex:t ?t . }
  OPTIONAL { ?_x ex:u ?u . }
} ORDER BY ?s ?t ?u
