INSERT {
	example:a a example:A ;
	    example:langString "foo"@en ;
	    example:string "bar" .

	example:b a example:A ;
	    example:langString "foo"@fr ;
	    example:string "baz" .

	example:c a example:A ;
	    example:langString "foo" ;
	    example:string "bla"@es .

	example:d a example:A ;
	    example:langString "bleh"@en .
}
