.TH tracker-preferences 1 "November, 2007" GNU "User Commands"

.SH NAME
tracker-preferences \- Preferences editor for trackerd

.SH SYNOPSIS
.B tracker-preferences

.SH DESCRIPTION
.B tracker-preferences
is a graphical configuration front end for the
.BR trackerd (1)
indexer and search daemon.

.SH SEE ALSO
.BR tracker-search-tool (1),
.BR trackerd (1).
