.TH tracker-meta-folder 1 "July, 2007" GNU "User Commands"

.SH NAME
tracker-meta-folder \- return list of files indexed by tracker for a
folder with their value for the selected properties

.SH SYNOPSIS
.B tracker-meta-folder
\-p FOLDER [Properties]

.SH DESCRIPTION
.B tracker-meta-folder
shows in stdout the list of files and their values for the selected
properties indexed by tracker and stored under the
folder provided as parameter. 

.SH OPTIONS
.TP
\-p FOLDER
The path you are asking for.

.TP
PROPERTIES
A list of properties to show per file. For more information on valid
properties see
.BR tracker-services (1).

.SH EXAMPLES
.TP
The mimetypes of all the files in the test/ folder:
.BR
$ tracker-meta-folder /x/y/test File:Mime

.SH SEE ALSO
.BR trackerd (1).
.BR tracker-services (1)
