.TH HTMLESS 1 "Januar 10, 2007"

.SH NAME
htmless \- html to text converter

.SH SYNOPSIS
\fBhtmless\fR \fIfilename.html\fR [\fIoutput_text\fR] [\fIoutput_tag\fR]

.SH DESCRIPTION
.B htmless
takes a html file as input and produces two files as output.
One contains the text dump of the html file, the other all html tags.
.br
.B trackerd
uses 
.B htmless
for indexing html files.

.SH OPTIONS
If the second and third argument are empty, 
.B htmless
creates two files named \fIfilename.txt\fR and \fIfilename_t.txt\fR in the 
same directory as the original file.
.br
\fIfilename.txt\fR contains the text dump, \fIfilename_t.txt\fR the html tags.
.br
Otherwise the filenames as passed on the command line are used for the output.

.SH SEE ALSO
.BR trackerd (1),
.BR tracker-search (1).

.SH AUTHOR
htmless was written by Stephen M. Orth <sorth@oz.net>.
.PP
This manual page was written by Michael Biebl <biebl@debian.org>,
for the Debian project (but may be used by others).
