site_name: Tracker
theme: cinder
docs_dir: ./website

nav:
  - Home: 'index.md'
  - Overview: 'overview.md'
  - FAQ: 'faq.md'
  - Community: 'community.md'
  - Documentation:
      User documentation: 'docs/user.md'
      Developer documentation: 'docs/developer.md'
      Commandline documentation: 'docs/commandline.md'

markdown_extensions:
  - admonition
