.TH TRACKER-TAG 1 "Januar 10, 2007"

.SH NAME
tracker-tag \- command line tool for setting and searching tags/keywords

.SH SYNOPSIS
\fBtracker-tag\fR [\fIoptions\fR] \fIFILE\fR...

.SH DESCRIPTION
.B tracker-tag
allows you to modify the tags that are associated with a file.
The actual information is stored in a 
.B tracker
database.

.SH OPTIONS
.TP
.B \-?, \-\-help
Show summary of options.
.TP
.B \-a, \-\-add=TAG
Add specified tag to a file.
.TP
.B \-r, \-\-remove=TAG
Remove specified tag from a file.
.TP
.B \-R, \-\-remove-all
Remove all tags associated with a file.
.TP
.B \-l, \-\-list
List all tags associated with a file.
.br
If no file name is given, all known tags and their count is listed.
.TP
.B \-s, \-\-search=TAG
Search for files matching the given tag.

.SH SEE ALSO
.BR trackerd (1).

.SH AUTHOR
tracker-tag was written by Jamie McCracken <jamiemcc@gnome.org>.
.PP
This manual page was written by Michael Biebl <biebl@debian.org>,
for the Debian project (but may be used by others).
