.TH tracker-meta-folder 1 "September 2006" "Version 0.5"
.SH NAME
tracker-meta-folder \- return list of files indexed by tracker for a folder
.SH SYNOPSIS
.B tracker-meta-folder
folder
.SH DESCRIPTION
.B tracker-meta-folder
returns the list of files indexed by tracker and stored under the folder provided as parameter.
.SH AUTHOR
Baptiste Mille-Mathias <baptiste.millemathias@gmail.com>

