.TH tracker-query 1 "September 2006" "Version 0.5"
.SH NAME
tracker-query \- command line tool to query tracker database 
.SH SYNOPSIS
.B tracker-query
.I query-file.rdf
.SH DESCRIPTION
.B tracker-query
searches documents using a query file (in rdf format) provided as parameter, and
returns the documents matching the criteria of the query file.
.SH AUTHOR
Baptiste Mille-Mathias <baptiste.millemathias@gmail.com>
.SH "SEE ALSO"
trackerd (1)
