.TH TRACKER-THUMBNAILER 1 "Januar 10, 2007"

.SH NAME
tracker-thumbnailer \- create freedesktop.org compliant thumbnails

.SH SYNOPSIS
\fBtracker-thumbnailer\fR \fIFILE\fR \fIMIMETYPE\fR \fIICONSIZE\fR 

.SH DESCRIPTION
.B tracker-thumbnailer
takes an image file as input and produces a thumbnail which is compliant
to the freedesktop.org thumbnail specification.
.br
It relies on external tools like \fBconvert\fR to do the 
actual transformation.
.PP
.B tracker-thumbnailer
is called by 
.B trackerd
to create thumbnails which are then used by frontends like
.B tracker-search-tool
to illustrate the search results.

.SH OPTIONS
.TP
\fIFILE\fR
Image file for which a thumbnail should be created.
.TP
\fIMIMETYPE\fR
Mime type of the image/document, e.g. image/png or application/pdf.
If no thumbnailer is installed for this mime type, \fBtracker-thumbnailer\fR
will output a error message.
.TP
\fIICONSIZE\fR
Size of the generated thumbnail.
Currently supported is only \fBnormal\fR, which is 128x128 pixel.

.SH SEE ALSO
.BR trackerd (1),
.BR tracker-search-tool (1),
.BR convert (1).

.SH AUTHOR
tracker-thumbnailer was written by Edward Duffy <eduffy@gmail.com>.
.PP
This manual page was written by Michael Biebl <biebl@debian.org>,
for the Debian project (but may be used by others).
