.TH tracker-applet 1 "November, 2007" GNU "User Commands"

.SH NAME
tracker-applet \- The tracker tray-icon and on-click-search-entry

.SH SYNOPSIS
.B tracker-applet

.SH DESCRIPTION
.B tracker-applet
is a
.BR trackerd (1)
system tray icon, meant to provide a fast way of accessing tracker's
database, configuring tracker through
.BR tracker-preferences
and displaying information, by means of popups, icon changes and the
statistics page to the user.

.SH SEE ALSO
.BR tracker-search-tool (1),
.BR trackerd (1).
