INSERT DATA {
  example:a  a example:A ;
             example:stringMultivalued 'foo' ;
             example:stringMultivalued 'bar' ;
             example:stringMultivalued 'baz' .
  example:b  a example:A ;
             example:stringMultivalued 'baa' .
}

DELETE WHERE {
  example:a  example:stringMultivalued ?anything .
}
